{
 "title": "Actor benchmark",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "System Under Test", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Message throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(app_message_total[$__rate_interval]))",
     "legendFormat": "throughput"
    }
   ]
  },
  {
   "title": "Message 99p latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(app_message_latency_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "99p"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_message_latency_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "95p"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(app_message_latency_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "50p"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(app_errors_total[$__rate_interval]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "SUT pods CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", pod=~\".*sut.*\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", pod=~\".*sut.*\"}[$__rate_interval]))",
     "legendFormat": "total"
    },
    {
     "expr": "max_over_time(sum(rate(container_cpu_usage_seconds_total{image!=\"\", pod=~\".*sut.*\"}[$__rate_interval]))[5m:15s])",
     "legendFormat": "max over 5 min"
    }
   ]
  },
  {
   "title": "SUT pods memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\", pod=~\".*sut.*\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\", pod=~\".*sut.*\"})",
     "legendFormat": "total"
    },
    {
     "expr": "max_over_time(sum(container_memory_usage_bytes{image!=\"\", pod=~\".*sut.*\"})[5m:15s])",
     "legendFormat": "max over 5 min"
    }
   ]
  },
  { "title": "Test runner", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Test runner pods CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", pod=~\"test-runner.*\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", pod=~\"test-runner.*\"}[$__rate_interval]))",
     "legendFormat": "total"
    },
    {
     "expr": "max_over_time(sum(rate(container_cpu_usage_seconds_total{image!=\"\", pod=~\"test-runner.*\"}[$__rate_interval]))[5m:15s])",
     "legendFormat": "max over 5 min"
    }
   ]
  },
  {
   "title": "Test runner pods memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\", pod=~\"test-runner.*\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\", pod=~\"test-runner.*\"})",
     "legendFormat": "total"
    },
    {
     "expr": "max_over_time(sum(container_memory_usage_bytes{image!=\"\", pod=~\"test-runner.*\"})[5m:15s])",
     "legendFormat": "max over 5 min"
    }
   ]
  },
  { "title": "K8S", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Node CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes - node_memory_SReclaimable_bytes) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}